version: '3.1'

services:
  mysql:
    image: mysql:8.0.18
    restart: always
    expose:
      - '3306'
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: "alfa_db"
      MYSQL_USER: "app"
      MYSQL_PASSWORD: "YES"
      MYSQL_ROOT_PASSWORD: "password"